### ISSUE TITLE
Improve NavigationDrawer documentation

### ISSUE THREAD

**Issue by carlosforero** [mlaursen/react-md-docs#1]
The documentation about NavigationDrawer is very complicated. The sample code should be easier to understand.

I can prepare a PR next week.

**Comment by mlaursen** [comment]
It probably wasn't a good idea of using the source code for my site as the example, but I was lazy :) I would appreciate a much simpler example for Navigation Drawers. If you have an idea of a nice way to demo that example as well, that would be great! I wasn't sure how to handle it since the NavigationDrawer is a full page layout component.

Thanks!
